// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analysis.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAnalysisRuns = `-- name: CountAnalysisRuns :one
SELECT count(*)
FROM analysis_runs
`

func (q *Queries) CountAnalysisRuns(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAnalysisRuns)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeliveryAttempts = `-- name: CountDeliveryAttempts :one
SELECT count(*)
FROM delivery_attempts
`

func (q *Queries) CountDeliveryAttempts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDeliveryAttempts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnalysisRun = `-- name: GetAnalysisRun :one
SELECT id, input_hash, rule_version, report, indicators, created_at
FROM analysis_runs
WHERE id = $1
`

func (q *Queries) GetAnalysisRun(ctx context.Context, id int64) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, getAnalysisRun, id)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.InputHash,
		&i.RuleVersion,
		&i.Report,
		&i.Indicators,
		&i.CreatedAt,
	)
	return i, err
}

const getAnalysisRunByInputHash = `-- name: GetAnalysisRunByInputHash :one
SELECT id, input_hash, rule_version, report, indicators, created_at
FROM analysis_runs
WHERE input_hash = $1
`

func (q *Queries) GetAnalysisRunByInputHash(ctx context.Context, inputHash []byte) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, getAnalysisRunByInputHash, inputHash)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.InputHash,
		&i.RuleVersion,
		&i.Report,
		&i.Indicators,
		&i.CreatedAt,
	)
	return i, err
}

const getDeliveryAttemptByKey = `-- name: GetDeliveryAttemptByKey :one
SELECT id, analysis_run_id, idempotency_key, status, provider_message_id, attempt_count, last_error, created_at, updated_at
FROM delivery_attempts
WHERE idempotency_key = $1
`

func (q *Queries) GetDeliveryAttemptByKey(ctx context.Context, idempotencyKey string) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, getDeliveryAttemptByKey, idempotencyKey)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.AnalysisRunID,
		&i.IdempotencyKey,
		&i.Status,
		&i.ProviderMessageID,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAnalysisRun = `-- name: InsertAnalysisRun :one
INSERT INTO analysis_runs (input_hash, rule_version, report, indicators)
VALUES ($1, $2, $3, $4)
ON CONFLICT (input_hash) DO NOTHING
RETURNING id, input_hash, rule_version, report, indicators, created_at
`

type InsertAnalysisRunParams struct {
	InputHash   []byte `json:"input_hash"`
	RuleVersion string `json:"rule_version"`
	Report      []byte `json:"report"`
	Indicators  []byte `json:"indicators"`
}

func (q *Queries) InsertAnalysisRun(ctx context.Context, arg InsertAnalysisRunParams) (AnalysisRun, error) {
	row := q.db.QueryRow(ctx, insertAnalysisRun,
		arg.InputHash,
		arg.RuleVersion,
		arg.Report,
		arg.Indicators,
	)
	var i AnalysisRun
	err := row.Scan(
		&i.ID,
		&i.InputHash,
		&i.RuleVersion,
		&i.Report,
		&i.Indicators,
		&i.CreatedAt,
	)
	return i, err
}

const insertDeliveryAttempt = `-- name: InsertDeliveryAttempt :one
INSERT INTO delivery_attempts (analysis_run_id, idempotency_key, status)
VALUES ($1, $2, 'PENDING')
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, analysis_run_id, idempotency_key, status, provider_message_id, attempt_count, last_error, created_at, updated_at
`

type InsertDeliveryAttemptParams struct {
	AnalysisRunID  int64  `json:"analysis_run_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) InsertDeliveryAttempt(ctx context.Context, arg InsertDeliveryAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, insertDeliveryAttempt, arg.AnalysisRunID, arg.IdempotencyKey)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.AnalysisRunID,
		&i.IdempotencyKey,
		&i.Status,
		&i.ProviderMessageID,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :one
UPDATE delivery_attempts
SET status = 'FAILED',
    attempt_count = attempt_count + 1,
    last_error = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, analysis_run_id, idempotency_key, status, provider_message_id, attempt_count, last_error, created_at, updated_at
`

type MarkDeliveryFailedParams struct {
	ID        int64       `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, markDeliveryFailed, arg.ID, arg.LastError)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.AnalysisRunID,
		&i.IdempotencyKey,
		&i.Status,
		&i.ProviderMessageID,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliverySucceeded = `-- name: MarkDeliverySucceeded :one
UPDATE delivery_attempts
SET status = 'SUCCEEDED',
    provider_message_id = $2,
    attempt_count = attempt_count + 1,
    last_error = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, analysis_run_id, idempotency_key, status, provider_message_id, attempt_count, last_error, created_at, updated_at
`

type MarkDeliverySucceededParams struct {
	ID                int64       `json:"id"`
	ProviderMessageID pgtype.Text `json:"provider_message_id"`
}

func (q *Queries) MarkDeliverySucceeded(ctx context.Context, arg MarkDeliverySucceededParams) (DeliveryAttempt, error) {
	row := q.db.QueryRow(ctx, markDeliverySucceeded, arg.ID, arg.ProviderMessageID)
	var i DeliveryAttempt
	err := row.Scan(
		&i.ID,
		&i.AnalysisRunID,
		&i.IdempotencyKey,
		&i.Status,
		&i.ProviderMessageID,
		&i.AttemptCount,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
