// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalysisRun struct {
	ID          int64              `json:"id"`
	InputHash   []byte             `json:"input_hash"`
	RuleVersion string             `json:"rule_version"`
	Report      []byte             `json:"report"`
	Indicators  []byte             `json:"indicators"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AppSetting struct {
	SettingKey   string             `json:"setting_key"`
	SettingValue string             `json:"setting_value"`
	IsSecret     bool               `json:"is_secret"`
	Version      int64              `json:"version"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryAttempt struct {
	ID                int64              `json:"id"`
	AnalysisRunID     int64              `json:"analysis_run_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	Status            string             `json:"status"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	AttemptCount      int32              `json:"attempt_count"`
	LastError         pgtype.Text        `json:"last_error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
