// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AnalysisRun struct {
	ID           int64              `json:"id"`
	InputHash    []byte             `json:"input_hash"`
	RuleVersion  string             `json:"rule_version"`
	Report       []byte             `json:"report"`
	Indicators   []byte             `json:"indicators"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Phase        pgtype.Text        `json:"phase"`
	PrimaryAsset pgtype.Text        `json:"primary_asset"`
	WindowType   pgtype.Text        `json:"window_type"`
	WindowStart  pgtype.Timestamptz `json:"window_start"`
	WindowEnd    pgtype.Timestamptz `json:"window_end"`
	AsOfBucket   pgtype.Timestamptz `json:"as_of_bucket"`
	Bundle       []byte             `json:"bundle"`
}

type AnalysisScore struct {
	ID            int64              `json:"id"`
	AnalysisRunID int64              `json:"analysis_run_id"`
	ScoreType     string             `json:"score_type"`
	RuleVersion   string             `json:"rule_version"`
	PrimaryAsset  string             `json:"primary_asset"`
	Phase         string             `json:"phase"`
	WindowType    string             `json:"window_type"`
	ComponentSet  []string           `json:"component_set"`
	Value         pgtype.Numeric     `json:"value"`
	Direction     pgtype.Text        `json:"direction"`
	CoveragePct   int16              `json:"coverage_pct"`
	ConfidenceMax string             `json:"confidence_max"`
	Payload       []byte             `json:"payload"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type AppSetting struct {
	SettingKey   string             `json:"setting_key"`
	SettingValue string             `json:"setting_value"`
	IsSecret     bool               `json:"is_secret"`
	Version      int64              `json:"version"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryAttempt struct {
	ID                int64              `json:"id"`
	AnalysisRunID     int64              `json:"analysis_run_id"`
	IdempotencyKey    string             `json:"idempotency_key"`
	Status            string             `json:"status"`
	ProviderMessageID pgtype.Text        `json:"provider_message_id"`
	AttemptCount      int32              `json:"attempt_count"`
	LastError         pgtype.Text        `json:"last_error"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type MemoryTrendHistory struct {
	ID                int64              `json:"id"`
	AnalysisRunID     int64              `json:"analysis_run_id"`
	RuleVersion       string             `json:"rule_version"`
	PrimaryAsset      string             `json:"primary_asset"`
	SessionDate       pgtype.Date        `json:"session_date"`
	PreviousState     string             `json:"previous_state"`
	State             string             `json:"state"`
	DayClassification string             `json:"day_classification"`
	Transitioned      bool               `json:"transitioned"`
	SupportiveStreak  int32              `json:"supportive_streak"`
	AdverseStreak     int32              `json:"adverse_streak"`
	Reason            string             `json:"reason"`
	ConfidenceMax     string             `json:"confidence_max"`
	EvidenceRefs      []byte             `json:"evidence_refs"`
	Payload           []byte             `json:"payload"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
