// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT setting_key, setting_value, is_secret, version, updated_at
FROM app_settings
WHERE setting_key = $1
`

func (q *Queries) GetSetting(ctx context.Context, settingKey string) (AppSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, settingKey)
	var i AppSetting
	err := row.Scan(
		&i.SettingKey,
		&i.SettingValue,
		&i.IsSecret,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSetting = `-- name: UpsertSetting :one
INSERT INTO app_settings (setting_key, setting_value, is_secret)
VALUES ($1, $2, $3)
ON CONFLICT (setting_key) DO UPDATE
SET setting_value = EXCLUDED.setting_value,
    is_secret = EXCLUDED.is_secret,
    version = app_settings.version + 1,
    updated_at = now()
RETURNING setting_key, setting_value, is_secret, version, updated_at
`

type UpsertSettingParams struct {
	SettingKey   string `json:"setting_key"`
	SettingValue string `json:"setting_value"`
	IsSecret     bool   `json:"is_secret"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) (AppSetting, error) {
	row := q.db.QueryRow(ctx, upsertSetting, arg.SettingKey, arg.SettingValue, arg.IsSecret)
	var i AppSetting
	err := row.Scan(
		&i.SettingKey,
		&i.SettingValue,
		&i.IsSecret,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
